apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project
  labels:
    app: devops-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
      - name: devops-project
        image: chandanvura/devops-project:v1
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"